<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mage2typo3"
 *
 * Auto generated by Extension Builder 2019-04-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Mage2Typo3',
    'description' => 'supplies a product import from Magento 2 to Typo3',
    'category' => 'plugin',
    'author' => 'Tobias Quadflieg',
    'author_email' => 'Quadflieg@graphodata.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
