<?php

namespace Graphodata\Mage2typo3\Controller\Be;

use TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface;
use TYPO3\CMS\Extbase\Mvc\Controller\ActionController;
use TYPO3\CMS\Extbase\Mvc\View\ViewInterface;

class CategoriesController extends ActionController
{
    public function injectConfigurationManager(ConfigurationManagerInterface $configurationManager)
    {
        parent::injectConfigurationManager($configurationManager); // TODO: Change the autogenerated stub
    }

    public function injectObjectManager(\TYPO3\CMS\Extbase\Object\ObjectManagerInterface $objectManager)
    {
        parent::injectObjectManager($objectManager); // TODO: Change the autogenerated stub
    }

    protected function initializeView(ViewInterface $view)
    {
        parent::initializeView($view); // TODO: Change the autogenerated stub
    }

    protected function initializeAction()
    {
        parent::initializeAction(); // TODO: Change the autogenerated stub
    }

    public function listAction()
    {

    }

    public function showAction()
    {

    }
}
